table Measure_Table
	lineageTag: 70524cf4-8171-4da2-a503-0945f627d08e

	measure 'Recognized Revenue' =
			
			CALCULATE(
			    SUM(gold_fact_sales[net_sales]),
			    NOT gold_fact_sales[order_status] IN {"cancelled","refunded"}
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 12e93bc7-8ac9-4021-8b7c-457616c6a8da

		changedProperty = Name

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Gross Revenue' =
			
			SUM(gold_fact_sales[gross_sales])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 4a9495a3-e4d8-4665-bcb4-a67f0b3e7601

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure Orders =
			
			DISTINCTCOUNT(gold_fact_sales[order_id])
		formatString: 0
		lineageTag: 1e2ea9ab-3d7f-4313-b4a9-209b7b99fe30

	measure 'Recognized Orders' =
			
			CALCULATE(
			    DISTINCTCOUNT(gold_fact_sales[order_id]),
			    NOT gold_fact_sales[order_status] IN {"cancelled","refunded"}
			)
		formatString: 0
		lineageTag: 1f2fe185-14ad-4753-b3f1-5f5ae1554a75

	measure Units =
			
			SUM(gold_fact_sales[quantity])
		formatString: 0
		lineageTag: 9c5fe969-74ad-48b3-817f-0eea6ddc2092

	measure AOV =
			
			DIVIDE([Recognized Revenue], [Recognized Orders])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: d519ada3-dc98-4bc5-9302-82ed82f0386a

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Estimated Gross Profit' =
			
			SUMX(
			    gold_fact_sales,
			    gold_fact_sales[net_sales] -
			    RELATED(gold_dim_product[unit_cost]) * gold_fact_sales[quantity]
			)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 47e6ab85-1502-4da1-9d04-b404da9b1704

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Lifetime Orders' =
			
			CALCULATE(
			    DISTINCTCOUNT(gold_fact_sales[order_id]),
			    ALLEXCEPT(gold_dim_customer, gold_dim_customer[customer_id])
			)
		formatString: 0
		lineageTag: 3bea00e5-2ddd-4013-bfba-a0076bfc35e6

	measure 'Revenue % of Total' =
			
			DIVIDE(
			    [Recognized Revenue],
			    CALCULATE([Recognized Revenue], ALL(gold_dim_customer[Order_Bucket]))
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 84499fd3-7120-4bae-9a96-02da28a6a9da

	partition Measure_Table = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				  #"Removed Columns" = Table.RemoveColumns(Source, {"Column1"})
				in
				  #"Removed Columns"

	annotation PBI_ResultType = Table

