table 'Compensation Analysis_Measures'
	lineageTag: c934b50f-7253-4b44-af0a-7726923a885a

	measure 'Average Comp Salary' =
			
			AVERAGE ( gold_dim_employee[salary] )
		lineageTag: 79397b10-50c0-47a9-8590-5eadb23100b6

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median Salary' =
			
			MEDIAN ( gold_dim_employee[salary] )
		lineageTag: 526657fb-1ea6-4f7f-9e53-300eab813c75

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min Salary' =
			
			MIN ( gold_dim_employee[salary] )
		formatString: 0
		lineageTag: 8ea6899a-3321-4092-a565-04b87410a6fd

	measure 'Max Salary' =
			
			MAX ( gold_dim_employee[salary] )
		formatString: 0
		lineageTag: eb9e96b4-b941-4b52-b289-36e0cbe21847

	measure 'Salary Range' =
			
			[Max Salary] - [Min Salary]
		formatString: 0
		lineageTag: e71a4351-044a-474d-a476-dcc769f8dab7

	measure 'Average Tenure' =
			
			AVERAGE ( gold_dim_employee[tenure_years] )
		lineageTag: 84cbfd49-2325-47c5-a4a9-ad012f79ab5b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Salary per Tenure Year' =
			
			DIVIDE ( [Average Salary], [Average Tenure] )
		lineageTag: aa0c8293-3acd-422e-94fa-012fdd079373

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Department Avg Salary' =
			
			CALCULATE (
			    [Average Salary],
			    ALLEXCEPT ( gold_dim_employee, gold_dim_employee[department_id] )
			)
		lineageTag: a862356b-0e7b-4d20-854a-d20ef60eb135

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Salary Variance from Dept Avg' =
			
			AVERAGE ( gold_dim_employee[salary] ) - [Department Avg Salary]
		lineageTag: ef3181b3-12a5-4dc9-8375-8ef928d14c67

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Compensation Analysis_Measures' = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				  #"Removed Columns" = Table.RemoveColumns(Source, {"Column1"})
				in
				  #"Removed Columns"

	annotation PBI_ResultType = Table

