table Workforce_Measures
	lineageTag: 591b4c0c-e731-4c8d-886d-189af2220069

	measure 'Turnover Rate' =
			
			DIVIDE ( [Inactive Employees], [Total Headcount] )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: a117b6a5-627a-4f5b-b222-6505ddd03161

		changedProperty = Name

	measure 'Total Headcount' =
			
			DISTINCTCOUNT ( gold_dim_employee[employee_id] )
		formatString: 0
		lineageTag: 4cea2844-ec62-47e8-a8d1-78781db5690a

		changedProperty = Name

	measure 'Inactive Employees' =
			
			[Total Headcount] - [Active Employees]
		formatString: 0
		lineageTag: 507e23a3-e861-4b93-84e4-f02036e3b5c9

		changedProperty = Name

	measure 'Active Employees' =
			
			CALCULATE (
			    DISTINCTCOUNT ( gold_dim_employee[employee_id] ),
			    gold_dim_employee[is_active] = TRUE()
			)
		formatString: 0
		lineageTag: 3d456e92-8b35-409d-9334-53ed1aa3d1a4

		changedProperty = Name

	measure 'Active Employees_2' =
			
			CALCULATE (
			    DISTINCTCOUNT ( gold_dim_employee[employee_id] ),
			    gold_dim_employee[is_active] = "TRUE"
			)
		formatString: 0
		lineageTag: 277871d7-8b5c-4b07-bab6-db334f94cc33

		changedProperty = Name

	measure 'Actual Active Headcount' =
			
			[Active Employees]
		formatString: 0
		lineageTag: 983b2ad2-1e23-4b04-9026-c7ba4af500ab

		changedProperty = Name

	measure 'Actual Headcount' =
			
			[Total Headcount]
		formatString: 0
		lineageTag: c4e9a15d-fec2-4812-a05d-3f86abb03f5a

		changedProperty = Name

	measure 'Budgeted Headcount' =
			
			SUM ( gold_dim_department[head_count_budget] )
		formatString: 0
		lineageTag: 32a0068b-74ea-4e4c-82b3-6509a2c568fe

	measure 'Headcount Variance' =
			
			[Actual Headcount] - [Budgeted Headcount]
		formatString: 0
		lineageTag: b3b9c173-96fa-47dc-843a-75460b6a6ec8

	measure 'Headcount Variance %' =
			
			DIVIDE ( [Headcount Variance], [Budgeted Headcount] )
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 9e150805-985d-4e16-96f0-e7cf6aa42140

	partition Workforce_Measures = m
		mode: import
		source =
				let
				  Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				  #"Removed Columns" = Table.RemoveColumns(Source, {"Column1"})
				in
				  #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

